### ISSUE TITLE
5.x兼容性问题

### ISSUE THREAD

**Issue by findhappyx** [rrrfff/AndHook#11]
这个库在6.x和7.x上面兼容性还是很好的，但5.x崩溃率超高，基本不能用，不知道什么原因

**Comment by rrrfff** [comment]
5.x的ArtMethod是个Object, 可能与这有关。
能否提供具体点的信息，比如HOOK点、如何复现崩溃等等

**Comment by findhappyx** [comment]
我hook的是ViewGroup的removeAllViews函数，程序启动一段时间内hook也没问题，但过了一段时间后就会崩溃，我hook函数后再函数中打印了一条日志，其他什么都没干，然后就崩溃再打印日志这个地方了，类似如下，基本上必崩溃，你可以试试，我打印日志的函数是Log.wtf.

**Comment by findhappyx** [comment]
代码类似如下:    public void removeAllViews() {
        try {
            android.util.Log.wtf("", getClass().getName() + " ravs" + " oh");
        } catch (Throwable t) {
            t.printStackTrace();
        }

        try {
            AndHook.HookHelper.callVoidOrigin(this);
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }

**Comment by rrrfff** [comment]
能否提供apk以及相应的logcat给我, 可能removeAllViews需要其它条件配合才会触发, 目测测试未能复现
