### ISSUE TITLE
Hook后为什么会出现一个Trace进程？

### ISSUE THREAD

**Issue by findhappyx** [rrrfff/AndHook#12]
使用这个库hook成功后会出现一个Trace进程，而且这个进程还和zygote进程有关系，难道库中使用了ptrace以及相关的函数？不然为什么需要使用到调试函数？而且还和zygote进程有关。会有一个TracePid：xxx，这个进程居然是zygote进程

**Comment by findhappyx** [comment]
补充下，发现只在root过的手机上面出现，非Root过的不出现？这是什么原理？可以找个6.x的root手机一看就知道了

**Comment by rrrfff** [comment]
旧版本里包含了反调试ptrace(PTRACE_TRACEME, 0, 0, 0)， 但是前几次commit就被移除了，现在代码中使用到tracer的唯一一个点是用来暂停native线程, 以保证线程安全，但这只在jni层SuspendAllThreads被调用的情况下才会出现。其它情况原因暂不明

**Comment by findhappyx** [comment]
Good!
