### ISSUE TITLE
hook失败，提示incompatible method type

### ISSUE THREAD

**Issue by sudami** [rrrfff/AndHook#13]
@rrrfff 
大神，我在hook android.hardware.SystemSensorManager$**SensorEventQueue::dispatchSensorEvent**时，提示如下错误，求解

[该函数原型：http://androidxref.com/7.1.1_r6/xref/frameworks/base/core/java/android/hardware/SystemSensorManager.java#669](http://androidxref.com/7.1.1_r6/xref/frameworks/base/core/java/android/hardware/SystemSensorManager.java#669)

测试环境是armeabi、 安卓7.1.1

I/AndHook: SDK_INT = 25, IS_ART = true
I/AndHook: /system/bin/dex2oat disabled due to flag fast_dex = 1
E/AndHook: hook 0x70758e50 -> 0xf1ee2a64 failed, incompatible method type!
E/AndHook: failed to hook android.hardware.SystemSensorManager$SensorEventQueue::dispatchSensorEvent

**Comment by rrrfff** [comment]
函数原型没对上, dispatchSensorEvent是virtual, 不能替换成direct方法

**Comment by sudami** [comment]
就是说不能hook virtual函数，对不

**Comment by rrrfff** [comment]
不是, 是你的方法和要hook的方法类型要一致, virtual对应virtual

**Comment by sudami** [comment]
哦，我的替换方法声明的跟原虚函数不一样：
public static void MydispatchSensorEvent(int handle, float[] values, int inAccuracy, long timestamp)

原函数是这样的申明：
protected void dispatchSensorEvent(int handle, float[] values, int inAccuracy, long timestamp)

**Comment by rrrfff** [comment]
是的, static是direct

**Comment by sudami** [comment]
大神，虽然Hook成功了，但是在回调原函数时挂了：

```
protected void MydispatchSensorEvent(int handle, float[] values, int inAccuracy, long timestamp)
    {
        SLog.d(FixbugWXHelper.TAG, "call dispatchSensorEvent: handle:%d, values:%s, inAccuracy:%d", handle, values.toString(), inAccuracy);

        try
        {
            **AndHook.invokeVoidMethod(mSlot, mCls, handle, values, inAccuracy, timestamp);**
        }
        catch (Exception e)
        {
            e.printStackTrace();
            SLog.e(FixbugWXHelper.TAG, "Exception:%s", e.toString());
        }
    }
```

-------------------------------
W/System.err: java.lang.IllegalArgumentException: Expected receiver of type android.hardware.SystemSensorManager$SensorEventQueue, but got java.lang.Class<android.hardware.SystemSensorManager$SensorEventQueue>
W/System.err: at java.lang.reflect.Method.invoke(Native Method)
W/System.err: at andhook.lib.AndHook.invokeMethod(Native Method)
W/System.err: at andhook.lib.AndHook.invokeVoidMethod(AndHook.java:72)
W/System.err: at com.tencent.mm.voiceProxy.MydispatchSensorEvent(voiceProxy.java:29)
W/System.err: at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err: at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err: at android.os.Looper.loop(Looper.java:136)
W/System.err: at android.app.ActivityThread.main(ActivityThread.java:6290)
W/System.err: at java.lang.reflect.Method.invoke(Native Method)
W/System.err: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/voiceProxy[sfbug]: [MydispatchSensorEvent,(34)] Exception:java.lang.IllegalArgumentException: Expected receiver of type android.hardware.SystemSensorManager$SensorEventQueue, but got java.lang.Class<android.hardware.SystemSensorManager$SensorEventQueue>

**Comment by rrrfff** [comment]
你传错参数了, 对于virtual方法receiver要传this不能传类, 对于direct方法receiver要传null, 传类也行不过被忽略

**Comment by sudami** [comment]
this，从哪儿获取啊？

**Comment by sudami** [comment]
大神，可以了，哈哈哈，感谢感谢，结贴

**Comment by rrrfff** [comment]
纠正: 你传错参数了, 对于非static方法receiver要传this不能传类, 对于static方法receiver要传null, 传其它的也行不过最终会被忽略

AndHook.invokeVoidMethod(mSlot, this, handle, values, inAccuracy, timestamp);
