### ISSUE TITLE
Hooking into system apps (*.apk and/or *.jar) - Is that possible?

### ISSUE THREAD

**Issue by serajr** [rrrfff/AndHook#15]
Is AndHook able do that (like xposed framework does)?

**Comment by rrrfff** [comment]
No, it requires root privileges.

**Comment by serajr** [comment]
Thank you for your response!
I have a rooted device, so I would like to try this. I'd like to replace the return value (boolean) of an static method in services.jar (PackageManagerService class).
Is that still possible? If so, could you please help me out with a example? Thanks in advance!!

**Comment by rrrfff** [comment]
There are several ways of hooking into system processes, but none of them are integrated into AndHook. 
If you don't want to modify or replace files, just consider dynamic hook injection like https://github.com/evilsocket/arminject.
Hope this helps!
