### ISSUE TITLE
请问怎么集成在rom中呢

### ISSUE THREAD

**Issue by freesyscc** [rrrfff/AndHook#16]
请问怎么集成在rom中呢

**Comment by freesyscc** [comment]
集成在lineage os 14.1中  update-api时  提示  java.lang.class<?> clazz() default andhook.lib.AndHook.HookHelper.Hook    找不到符号
符号：变量Hook 位置 :类 hookhelper

**Comment by freesyscc** [comment]
大神  看到恢复下  微信13556817774

**Comment by rrrfff** [comment]
集成在rom中使用xposed即可
