### ISSUE TITLE
大佬lib不准备开源了咩

### ISSUE THREAD

**Issue by Qrilee** [rrrfff/AndHook#18]

**Comment by rrrfff** [comment]
原本是开源的, 不过后来基于同类开源项目的现状以及某些原因觉得并无多大必要, 所以还是选择了先闭源, 但原理都是公开的, 除原理之外无非是些见仁见智的东西, 不同的人有不同的封装方式, 加之稳定性值得商榷, 开源与否意义不大.

**Comment by rrrfff** [comment]
2.x版本使用的是方法替换+虚表替换, 在多dex下问题多、局限大, 已无深究的必要; 3.x版本使用native替换, 算是比较好的方案, 但仍存在问题, 主要还是编译器优化导致的, 目前frida使用的就是这种方案(但二者不存在交叉参考关系).
