### ISSUE TITLE
请问支持hook native方法吗？ test里面没看到有hook native方法的例子

### ISSUE THREAD

**Issue by kunshenglai** [rrrfff/AndHook#19]

**Comment by rrrfff** [comment]
https://github.com/rrrfff/AndHook/tree/master/app/src/main/jni

**Comment by kunshenglai** [comment]
![image](https://user-images.githubusercontent.com/3423625/34563255-e1eccf22-f18c-11e7-8ab0-05f92e4bdf6b.png)
想hook住java.lang.Object的finalize方法，但是不能复写这个方法，请问该怎么写呢？

**Comment by kunshenglai** [comment]
一定是导出的函数才可以hook么？ 非导出的函数行不行？

**Comment by rrrfff** [comment]
这和导出不导出没有直接关系, 没有导出的函数你要能知道函数地址也行
