### ISSUE TITLE
How does AndHook work?

### ISSUE THREAD

**Issue by hl46000** [rrrfff/AndHook#20]
I created mini rootchecker app use "access" function in c++ to test AndHook. I installed AndHook app and my rootchecker app and then launch AndHook app first. But when i open my app, it still detected device is root.
Can you tell me how do AndHook work?

**Comment by killer7Mod** [comment]
AndHook only makes porridge from the application in which this library is used, it does not affect other applications installed.

**Comment by hl46000** [comment]
if i can inject AndHook to another application, AndHook can work. Right?

**Comment by killer7Mod** [comment]
only modifying the application in question

**Comment by hl46000** [comment]
I used Xposed to inject AndHook to another application. Worked!!!

**Comment by lee5783** [comment]
@hl46000 can you guide me how to use xposed to inject andhook ?
