### ISSUE TITLE
How to hook Constructor function?

### ISSUE THREAD

**Issue by hl46000** [rrrfff/AndHook#21]
I need an example code to hook constructor function? Pls help me!!!

**Comment by rrrfff** [comment]
You cannot take the address of a constructor in C++, however, since constructor is actually a special member function with void return type, you can simply use 'void A::A_()' as a replacement of 'A::{ctor}'.

**Comment by wolfnightblack** [comment]
Please help, i need too

**Comment by rrrfff** [comment]
https://github.com/rrrfff/AndHook/blob/master/app/src/main/java/andhook/test/Constructor.java

**Comment by wolfnightblack** [comment]
I read, but i understand.
Example: i want hiden file : /system/app/Superuser.apk
I need an example code, please help me :(

**Comment by wolfnightblack** [comment]
In xposed have code:
 XposedHelpers.findAndHookConstructor("java.io.File", lpp.classLoader, String.class, new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                super.beforeHookedMethod(param);
                if((String)param.args[0] != null && param.args.length > 0) {
                    if (((String) param.args[0]).equals("/system/build.prop")) {
                        param.args[0] = AppSetting.pathDatabuild;
                        XposedBridge.log("File:" + param.getResult() + ":" + lpp.packageName);

                    }
                }
            }
        });
how to use in AndHook lib

**Comment by rrrfff** [comment]
AndHook is compatible with xposed and existing xposed code should be able to reuse. 
`
import andhook.lib.xposed.XC_MethodHook;
import andhook.lib.xposed.XposedBridge;
import andhook.lib.xposed.XposedHelpers;

public final class Examples {
	public void doHook() {
		XposedHelpers.findAndHookConstructor(java.io.File.class, String.class,
				new XC_MethodHook() {
					@Override
					protected void beforeHookedMethod(MethodHookParam param)
							throws Throwable {
						// super.beforeHookedMethod(param);
						if (param.args.length > 0 && param.args[0] != null) {
							if (((String) param.args[0])
									.equals("/system/build.prop")) {
								param.args[0] = ""; // AppSetting.pathDatabuild;
								XposedBridge.log("File:" + param.getResult());
							}
						}
					}
				});
	}
}
`

**Comment by wolfnightblack** [comment]
if use with xposed and existing xposed code not bypass nativate check

**Comment by hl46000** [comment]
Hey, I know you use AndHook to bypass C/C++(Cheating Offer). Please don't talk in my issue.

**Comment by wolfnightblack** [comment]
OK sorry, i think you too :D

**Comment by hl46000** [comment]
If you want to use AndHook with another applications. You can use AndHook with Xposed. Worked, Thanks.

**Comment by hl46000** [comment]
I don't know you used AndHook to hook Java or C/C++. If you want to hook C/C++ you have to use C/C++ in JNI. If don't understand how to AndHook work, you can contact me. ;)

**Comment by wolfnightblack** [comment]
Hoang Long, Chắc bạn là người Việt Nam, mình tiếng anh kém lắm, hình như mình được biết lib này hook đc C/C++, không biết mình có thể liên hệ với bạn qua đâu nhỉ :)

**Comment by hl46000** [comment]
Viết Tiếng Việt từ đầu có tốt không, làm google dịch thấy mẹ:)) AndHook dựa trên CydiaSubstrate và một phần Xposed. Hook để làm gì thì đương nhiên ai cũng biết :v nên tốt nhất không nên bàn ở đây. Lib này viết ra không phải để hook mọi package như Xposed. Nó chỉ có tác dụng với chính cái app của nó. Nếu muốn hook C/C++ thì phải dùng C/C++ để hook trong JNI. Còn hook Java có thể dùng Xposed như cái Qchanger của anh ấy ;) Không thể dùng Java để hook C/C++ được. Các Lib khác trên github đều hoạt động tương tự. Mình có hỏi một vấn đề về cách hoạt động của AndHook trong issue trước. Mình cũng giải đáp cách nó có thể hook các package khác. Và cuối cùng, C/C++ không phải là mấu chốt để "lead". Thanks
https://www.facebook.com/HLongLE.IT

**Comment by wolfnightblack** [comment]
Vãi 2 cha Việt Nam ngu tiếng Anh mà vào chém như rồng, chắc bạn cũng biết mình rồi, hehe. Mình cũng đang nghĩ theo cách nghĩ của bạn, nhưng thằng assmin AKChange thì nó bảo là qua được, nên mình đang phân vân hướng. Đúng việc lead ko phải mấu chốt ở cái hàm C/C++ nhưng nó dùng để check chất lượng traffic. Không biết bạn có document nào cho việc dùng JNI hook ko nhỉ :)

**Comment by hl46000** [comment]
Mình tách biệt với cộng đồng mmo nên ai bảo như thế nào mình cũng không rõ. Nó hoạt động giống y như bên iOS. Vì dùng chung core. Mọi chương trình đều chạy từ trên xuống, và được load vào bộ nhớ, và vùng bộ nhớ của app nào được load thì chỉ có app đó can thiệp được thôi. Anh chỉ cần load lib AndHook trước khi load lib Hook của anh và phải load trước các lib khác của ứng dụng. Nếu AKChange hay XChanger đã làm được thì anh có thể hỏi. Nếu mấy người đó không trả lời thì hãy suy nghĩ vấn đề này: Xposed có thể hook vào mọi package thì ta có thể mượn nó để đẩy lib của mình vào.
Dùng JNI để hook thì cũng giống như dùng java thôi, tìm tên hàm cần hook rồi gọi đến hàm hook của AndHook. Viết bằng C hay C++ đều được.

**Comment by wolfnightblack** [comment]
Chà, bạn không cần tiền sao :(. Chắc mình cần đọc thêm code của thằng này xem sao :(. Cũng hok chuyên bên android, cái gì cũng tự mò cả :(

**Comment by hl46000** [comment]
Mình đi sau, nhưng nắm tốt cách app hoạt động, được cái không nắm được thời cơ. Vì một vài sai lầm nên giờ bắt đầu lại từ con số 0. Giờ xem như đua lại với đàn anh như anh hay các bậc tiền bối khác. Android trên giả lập không quay về được cái thời của nó nữa đâu. Sao không nghĩ đến đt.

**Comment by wolfnightblack** [comment]
Điện thoại làm rồi bạn, nhưng vẫn thích pc hơn vì chi phí rẻ và tiện hơn trong quản lý, bạn có kiến thức
Còn hướng đi, nếu cần tư vấn thì trao đổi với mình, đảm bảo ko bị tụt lại phía sau đâu :)

**Comment by hl46000** [comment]
Okay, có lẽ nên dừng bàn về vấn đề đó ở đây, ở đây thích hợp với code hơn :v

**Comment by baodev15** [comment]
Chào 2 anh nếu.. 2 anh có đọc đc cmt này thì cho em số liên hệ vs ạ.. Em thấy AndHook hook thẳng c++ mà k biết viết code thế nào ạ! https://www.facebook.com/xxxxxx565
