### ISSUE TITLE
How to hook this method

### ISSUE THREAD

**Issue by wolfnightblack** [rrrfff/AndHook#24]
# How to hook this method
_import java.lang.reflect.Method;                                                    
String serialnum = null;      
                                                                                                                                          
try {                                                                               
	Class<?> c = Class.forName("android.os.SystemProperties");        	 
	Method get = c.getMethod("get", String.class, String.class );                     
	serialnum = (String)(   get.invoke(c, "ro.serialno", "unknown" )  );              
}                                                                                 
catch (Exception ignored)                                                         
{                               
}

 _@AndHook.HookHelper.Hook(value = "android.os.SystemProperties")
    private static String get(final Class<?> clss, final String name, String def) {
        if (name.equals("ro.serialno") || name.equals("ro.boot.serialno"))
            return "FakeSerial";
        return AndHook.HookHelper.invokeObjectOrigin(null, name, def);
    }_

**Comment by rrrfff** [comment]
？

**Comment by killer7Mod** [comment]
@hook(clazz=SystemProperties.class)

**Comment by wolfnightblack** [comment]
I want hook this method
_import java.lang.reflect.Method;
String serialnum = null;

try {
Class<?> c = Class.forName("android.os.SystemProperties");
Method get = c.getMethod("get", String.class, String.class );
serialnum = (String)( get.invoke(c, "ro.serialno", "unknown" ) );
}
catch (Exception ignored)
{
}
