### ISSUE TITLE
Hook系统函数咋没效果?

### ISSUE THREAD

**Issue by mdalvik** [rrrfff/AndHook#3]
我的手机小米4.4，hook自己写的类没问题，要hook系统的方法就不行了，比如hook activit的oncreate方法，

**Comment by rrrfff** [comment]
有测试代码吗？我这边测试是可以的

**Comment by mdalvik** [comment]
Method  m1 = Activity.class.getDeclaredMethod("onCreate",Bundle.class);
 Method  m2 = App.class.getMethod("activityOnCreate",Bundle.class);
如果上面的是Activity.class 的话 hook 是不行的
  Method  m1 = MainActivity.class.getDeclaredMethod("onCreate",Bundle.class);
 Method  m2 = App.class.getMethod("activityOnCreate",Bundle.class);
如果是MainActivity 是可以hook成功的.
哥们你这个代码直接下载下来 很多东西要改一下才能运行的.难道是我改的时候改错什么了吗

**Comment by rrrfff** [comment]
你改了什么代码呢？
另外我更新了测试代码https://raw.githubusercontent.com/rrrfff/AndHook/master/java/test/src/apk/andhook/test/AndTest.java，使用Activity.class也可以hook到，不过我在模拟器测试的，真机晚点看看

**Comment by mdalvik** [comment]
andhook.cpp下 
jclass clazz = env->FindClass("apk/andhook/DalvikHook"); 这里如果不改 是找不到class
JNINativeMethod gMethods[]  这里面的几个JNI 注册方法 在class 文件是找不到的 哥们你能把源代码更新下嘛. 当前项目下的源码如果下载下来不改动是无法运行的。

**Comment by rrrfff** [comment]
你先直接用 https://github.com/rrrfff/AndHook/releases/tag/v2.1 编译好lib试试？
jni源码因为后来加入的native hook部分还没做好，所以没同步上来

**Comment by mdalvik** [comment]
恩用你编译好的lib hook 是没问题得~ 先关注下,待源码同步了 继续学习,谢谢了
