### ISSUE TITLE
Help me.

### ISSUE THREAD

**Issue by nakcont** [rrrfff/AndHook#30]
`bool checkRooted () {
    ifstream f;
    f.open("/system/xbin/su");
    return f.good();
}`
AKHook cannot hook ifstream, pls help me.

**Comment by rrrfff** [comment]
What functions have you hooked?
`access` is unnecessary for `ifstream` to open a file.

**Comment by nakcont** [comment]
This function is check device rooted.
i want hook denied detect device rooted. AKHook(access) working for me. but AKHook(ifstream) not working.And if i use 
ifstream => detect root
access => not detect root.

**Comment by nakcont** [comment]
https://stackoverflow.com/questions/12774207/fastest-way-to-check-if-a-file-exist-using-standard-c-c11-c

exists_test0 cannot pass
exists_test1 passed
exists_test2 passed
exists_test3 passed

pls help me :(

**Comment by rrrfff** [comment]
`ifstream` is actually not a function and cannot be hooked.
In order to bypass root detection, you probably need to hook all related functions such as `open`, `openat` and so on.

**Comment by nakcont** [comment]
ok, thanks you.
