### ISSUE TITLE
Got error in andhook 3.5

### ISSUE THREAD

**Issue by wolfnightblack** [rrrfff/AndHook#31]
Hello all
I use andhook on IXposedHookLoadPackage call to method on htc M7 
public static void XposedLoadLib()
    {
        try {
            AndHook.ensureNativeLibraryLoaded();
             //System.loadLibrary("myjnihook");
            System.load("/data/data/andhook.ui/lib/libmyjnihook.so");
            XposedBridge.log("Load thành công myjnihook");
        } catch (Exception e) {
            XposedBridge.log("Lỗi: "+ e.getMessage());
        }
    }
And got error from xposed:
04-11 23:28:47.900 ?/SENTINEL_TAG( 3094): SENTINEL_MSG_LIBCUTILS
04-11 23:28:47.900 ?/SENTINEL_TAG( 3094): SENTINEL_MSG_LIBLOG
04-11 23:28:55.433 I/Xposed  ( 3596): ngon
04-11 23:28:55.525 E/Xposed  ( 3596): java.lang.ExceptionInInitializerError
04-11 23:28:55.525 E/Xposed  ( 3596): 	at andhook.test.Launcher.XposedLoadLib(Launcher.java:13)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at andhook.test.Launcher.handleLoadPackage(Launcher.java:31)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at android.os.Looper.loop(Looper.java:148)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at java.lang.reflect.Method.invoke(Native Method)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
04-11 23:28:55.525 E/Xposed  ( 3596): Caused by: java.lang.RuntimeException: incompatible platform
04-11 23:28:55.525 E/Xposed  ( 3596): 	at andhook.lib.AndHook.<clinit>(AndHook.java:27)
04-11 23:28:55.525 E/Xposed  ( 3596): 	... 17 more
04-11 23:28:55.525 E/Xposed  ( 3596): Caused by: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/data/andhook.ui/lib/libAndHook.so"
04-11 23:28:55.525 E/Xposed  ( 3596): 	at java.lang.Runtime.load(Runtime.java:332)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at java.lang.System.load(System.java:1069)
04-11 23:28:55.525 E/Xposed  ( 3596): 	at andhook.lib.AndHook.<clinit>(AndHook.java:20)
04-11 23:28:55.525 E/Xposed  ( 3596): 	... 17 more

**Comment by rrrfff** [comment]
Hi, have you tried the [test-release.apk](https://github.com/rrrfff/AndHook/releases/download/v3.5.1/test-release.apk) on the same device? And could you please provide me with more detailed log (before the Exception is thrown)?

**Comment by wolfnightblack** [comment]
Please see my edit, just call method load lib in xposed load
https://drive.google.com/file/d/1dJ3MlU81EGkC8my-1fPstmP6tiIN9_R3/view?usp=sharing
![image](https://user-images.githubusercontent.com/26843761/38634318-6573f126-3dec-11e8-903d-ee8680c33266.png)

**Comment by rrrfff** [comment]
You would better upload attachments to GitHub directly since Google Drive is not available for me at this time. Before JNI_ERR returned from JNI_OnLoad in "/data/data/andhook.ui/lib/libAndHook.so", there should be a log demonstrating the actual causes.

**Comment by wolfnightblack** [comment]
Sorry for this carelessness

[AndHook3.5.zip](https://github.com/rrrfff/AndHook/files/1901268/AndHook3.5.zip)

**Comment by wolfnightblack** [comment]
My new class
`
package andhook.test;

import andhook.lib.AndHook;
import de.robv.android.xposed.IXposedHookLoadPackage;
import de.robv.android.xposed.XposedBridge;
import de.robv.android.xposed.callbacks.XC_LoadPackage;

public class Launcher implements IXposedHookLoadPackage {

    public static void XposedLoadLib()
    {
        try {
            AndHook.ensureNativeLibraryLoaded();
            System.load("/data/data/andhook.ui/lib/libmyjnihook.so");
            XposedBridge.log("Load thành công myjnihook");
        } catch (Exception e) {
            XposedBridge.log("Error: "+ e.getMessage());
        }
    }

    @Override
    public void handleLoadPackage(XC_LoadPackage.LoadPackageParam loadPackageParam) throws Throwable {
        if(loadPackageParam.packageName.equals("app.xchanger.check"))
        {
            XposedBridge.log("FoundPackage");
            XposedLoadLib();
        }
    }
`

**Comment by rrrfff** [comment]
Unfortunately I am unable to reproduce this issue on my device, could you attach a full logcat again?
By the way, it seems that you are writing a xposed module, in which case AndHook is actually unnecessary.

**Comment by wolfnightblack** [comment]
Yes, i need to write new xposed module, but some android app detect xposed running so i have to create modified xposed module to hide it. I get this error on arm device, but passed on x86 device
Here is full log from xposed.
[xposed_error_20180412_143450.log](https://github.com/rrrfff/AndHook/files/1901830/xposed_error_20180412_143450.log)

**Comment by wolfnightblack** [comment]
Give me a QQ group if you have one

**Comment by rrrfff** [comment]
313845146

**Comment by wolfnightblack** [comment]
Added, please add me RLib
