### ISSUE TITLE
怎么Hook构造方法？

### ISSUE THREAD

**Issue by TIIEHenry** [rrrfff/AndHook#4]

**Comment by rrrfff** [comment]
getConstructor或getDeclaredConstructor, 之后和其它方法类似

**Comment by sudami** [comment]
getConstructor或getDeclaredConstructor 之后得到的是 Constructor类型，不是Method 类型，没法调用hook引擎啊，怎么办

**Comment by rrrfff** [comment]
@sudami 
https://github.com/rrrfff/AndHook/blob/master/test/app/src/main/java/andhook/test/Constructor.java

**Comment by sudami** [comment]
好滴，我研究研究，多谢大神，不懂再回来问 :-)
