### ISSUE TITLE
加载so报错

### ISSUE THREAD

**Issue by goforit007** [rrrfff/AndHook#5]
测试机器红米note3 
看不到so里面的逻辑

JNI_OnLoad: SDK_INT = 23, IS_ART = true
CheckArtMethodSize: ArtMethod size check failed[2] and cannot be fixed, SDK = 23

**Comment by rrrfff** [comment]
麻烦提取下系统libart.so

**Comment by goforit007** [comment]
[libart.so.zip](https://github.com/rrrfff/AndHook/files/1283717/libart.so.zip)

**Comment by rrrfff** [comment]
64位ArtMethod字段偏移计算有误, 麻烦你替换下面这个so, 然后把logcat的输出都贴上来看看?
[libandhook.zip](https://github.com/rrrfff/AndHook/files/1283991/libandhook.zip)

**Comment by goforit007** [comment]
测试了一个loadUrl函数，hook和callOrigin都通过了，应该是没问题了。
下面是loadso的日志。

E/hook: System.load libandhook.so
I/JNI_OnLoad: SDK_INT = 23, IS_ART = true
I/read: found /system/lib64/libart.so at 0x7f86fea000
I/caspriti.sxxdex: type=1400 audit(0.0:23630): avc: denied { execute } for path="/data/local/tmp/libandhook.so" dev="mmcblk0p46" ino=553832 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=file permissive=1
I/Init: base = 0x7f86fea000, endp = 0x7f875cf000, known = 0x7f8710eb8c
I/ReadSectionHeaders: load_bias = -176128
I/Init: JNI::ExceptionClear found at /system/lib64/libart.so, 0x7f86fea000
W/Init: invalid load_bias, diff = -8284, -2154908
W/__init_special_art_workaround: Moving GC notification is unavailable!
I/InitOffsets: finding class offsets...
I/InitOffsets: offset of class accessFlags = 44, vtable = 40
I/ensureClassInitialized: class initialized, clazz = 0x7fe69a9bb8, obj = 0x200031
I/ensureClassInitialized: class initialized, clazz = 0x7fe69a9bb8, obj = 0x31
I/__is_method_mapping_required: cls_origin = 0x708B0030, cls_target = 0x13051800, diff = 0x5D85E830
I/__native_hook_virtual: finding embedded vtable entry with jmethodID = 0x70ac0fb8...
I/__native_hook_virtual: setting eslot offset = 72
I/__native_hook: hook 0x70ac0fb8[virtual] -> 0x7f706e91d8 successfully!
I/__insert_method_mapping: method mapping inserted at 0
I/operator(): disabled moving gc 0x200001 0x130870d0
