### ISSUE TITLE
请问支持android6.0 arm64的机子吗？

### ISSUE THREAD

**Issue by williamsim** [rrrfff/AndHook#9]
jni Hook 支持android6.0 arm64的机子吗？如果可以的话，方便提供一下这方面的例子吗？谢谢

**Comment by williamsim** [comment]
jni Hook  支持android6.0 arm64的机子吗

**Comment by rrrfff** [comment]
理论性支持, demo见https://github.com/rrrfff/AndHook/tree/master/test

**Comment by williamsim** [comment]
@rrrfff 看了测试实例的jni hook代码不是很明白，可以写个关于Hook __system_property_get  的测试示例吗？谢谢了

**Comment by rrrfff** [comment]
@williamsim 这个你参考https://github.com/rrrfff/AndHook/blob/master/test/lib/src/main/jni/myjnihook.cpp中对access的处理即可.
